spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservercloud-config-hzl-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-hzl-test
# 保存格式必须为utf-8
© 2019 GitHub, Inc.