spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev 
  application:
    name: microservercloud-config-dev
---
spring:
  profiles: test 
  application:
    name: microservicecloud-config-test
